- .gitignore
- .npmignore
- README.md
- package.json
- pnpm-lock.yaml
published for https://www.npmjs.com/package/@nigg/eslint-plugin-cdk
> chore: publish npm

- src/__tests__/pascal-case-construct-id.test.ts
- src/no-import-private.mts
- src/pascal-case-construct-id.mts
> fix: eslint rules

- README.md
- src/__tests__/no-construct-stack-suffix.test.ts
- src/index.mts
- src/no-construct-stack-suffix.mts
> feat: add rule construct id does not contain the word `construct`

- README.md
- src/index.mts
> feat:  support recommended rules

- src/__tests__/no-construct-stack-suffix.test.ts
- src/__tests__/no-parent-name-construct-id-match.test.ts
- src/no-construct-stack-suffix.mts
- src/no-parent-name-construct-id-match.mts
> fix: does not support code written in methods

- .github/workflows/ci.yml
- docs/.vitepress/config.mts
- docs/index.md
- docs/ja/index.md
- docs/ja/rules/index.md
- docs/rules/index.md
> docs: Setting OGP

- CONGRIBUTING.md
> docs: add CONTRIBUTING.md

- .github/workflows/ci.yml
- CNAME
- docs/.vitepress/config.mts
> chore: configuration custom domain

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/question.yml
> chore: add ISSUE_TEMPLATE

- .vscode/settings.json
- docs/getting-started/example.md
- docs/getting-started/index.md
- docs/ja/getting-started/example.md
- docs/ja/getting-started/index.md
- docs/ja/index.md
- docs/ja/rules/index.md
- docs/ja/rules/no-class-in-interface.md
- docs/ja/rules/no-construct-stack-suffix.md
- docs/ja/rules/no-import-private.md
- docs/ja/rules/no-mutable-props-interface.md
- docs/ja/rules/no-mutable-public-fields.md
- docs/ja/rules/no-parent-name-construct-id-match.md
- docs/ja/rules/no-public-class-fields.md
- docs/ja/rules/pascal-case-construct-id.md
- docs/rules/index.md
- docs/rules/no-class-in-interface.md
- docs/rules/no-construct-stack-suffix.md
- docs/rules/no-import-private.md
- docs/rules/no-mutable-props-interface.md
- docs/rules/no-mutable-public-fields.md
- docs/rules/no-parent-name-construct-id-match.md
- docs/rules/no-public-class-fields.md
- docs/rules/pascal-case-construct-id.md
n/A
To reach more users by making documents easier to understand and read
Improved overall vitepress documentation.
> docs: update rule documents

- docs/ja/rules/index.md
- docs/rules/index.md
> docs: add strict rule

- docs/ja/rules/no-construct-stack-suffix.md
- docs/rules/no-construct-stack-suffix.md
- src/__tests__/no-construct-stack-suffix.test.ts
- src/rules/no-construct-stack-suffix.ts
> feat: add disallowedSuffixes option to `no-construct-stack-suffix` rule

- docs/ja/rules/no-variable-construct-id.md
- docs/rules/no-variable-construct-id.md
- src/__tests__/no-variable-construct-id.test.ts
- src/rules/no-variable-construct-id.ts
> fix: allow construct IDs to use variables within forEach

- eslint.config.js
- package.json
- pnpm-lock.yaml
> chore: update package

- CHANGELOG.md
- package.json
> chore: Release v2.0.0

- src/index.ts
> fix: update languageOptions.parser

- docs/ja/rules/no-parent-name-construct-id-match.md
- docs/rules/no-parent-name-construct-id-match.md
- src/__tests__/no-parent-name-construct-id-match.test.ts
- src/rules/no-parent-name-construct-id-match.ts
> feat: update "no-parent-name-construct-id-match" rule

- docs/.vitepress/config.mts
- package.json
- pnpm-lock.yaml
This PR introduces [vitepress-plugin-llms](https://github.com/okineadev/vitepress-plugin-llms).
Once this PR is merged, https://eslint-cdk-plugin.dev/llms.txt and https://eslint-cdk-plugin.dev/llms-full.txt will become available.
> feat: generate llms.txt and llms-full.txt

- eslint.config.js
> chore: update eslint.config.js

- VERSIONING_POLICY.md
> docs: update VERSIONING_POLICY

- .github/workflows/ci.yml
- VERSIONING_POLICY.md
- package.json
- pnpm-lock.yaml
> chore: update dependencies

- CHANGELOG.md
- VERSIONING_POLICY.md
- package.json
> chore: release v3.0.0

- src/rules/construct-constructor-property.ts
- src/rules/no-construct-in-interface.ts
- src/rules/no-construct-in-public-property-of-construct.ts
- src/rules/no-construct-stack-suffix.ts
- src/rules/no-import-private.ts
- src/rules/no-mutable-property-of-props-interface.ts
- src/rules/no-mutable-public-property-of-construct.ts
- src/rules/no-parent-name-construct-id-match.ts
- src/rules/no-variable-construct-id.ts
- src/rules/pascal-case-construct-id.ts
- src/rules/props-name-convention.ts
- src/rules/require-jsdoc.ts
- src/rules/require-passing-this.ts
- src/rules/require-props-default-doc.ts
- src/utils/createRule.ts
Closes N/A
Add document links to each rule
N/A
---
> chore: add link to each rule

- .github/workflows/ci.yml
Closes N/A
To automate npm publish.
---
> chore: npm publish with CI

- CHANGELOG.md
- package.json
> chore: release v3.1.0

- docs/ja/rules/require-props-default-doc.md
- src/rules/require-props-default-doc.ts
Closes N/A
Deleted due to unnecessary branching process.
---
> refactor: update require-props-default-doc rule

- CHANGELOG.md
- package.json
> chore: Release v3.2.0

- .gitignore
- CHANGELOG.md
- docs/.vitepress/config.mts
- docs/components/NextRecommendedItem.vue
- docs/ja/rules/index.md
- docs/ja/rules/no-unused-props.md
- docs/ja/rules/require-jsdoc.md
- docs/ja/rules/require-props-default-doc.md
- docs/rules/index.md
- docs/rules/no-unused-props.md
- docs/rules/require-jsdoc.md
- package.json
- src/__tests__/no-unused-props.test.ts
- src/index.ts
- src/rules/construct-constructor-property.ts
- src/rules/no-construct-in-public-property-of-construct.ts
- src/rules/no-construct-stack-suffix.ts
- src/rules/no-unused-props.ts
- src/rules/no-variable-construct-id.ts
- src/rules/pascal-case-construct-id.ts
- src/rules/props-name-convention.ts
- src/rules/require-jsdoc.ts
- src/rules/require-passing-this.ts
- src/rules/require-props-default-doc.ts
- src/utils/getConstructor.ts
- src/utils/getPropertyNames.ts
- src/utils/propsUsageTracker.ts
> main -> release

- .github/PULL_REQUEST_TEMPLATE.md
> chore: remove checklist section from pull request template

- docs/getting-started/index.md
- docs/ja/getting-started/index.md
- docs/ja/rules/no-construct-stack-suffix.md
- docs/ja/rules/no-parent-name-construct-id-match.md
- docs/ja/rules/no-unused-props.md
- docs/ja/rules/require-passing-this.md
- docs/rules/no-construct-stack-suffix.md
- docs/rules/no-parent-name-construct-id-match.md
- docs/rules/no-unused-props.md
- docs/rules/require-passing-this.md
- Update the rules docs
- update example in rule
- update options docs
---
> docs: update examples in rules and options documentation

- src/rules/no-construct-stack-suffix.ts
- src/rules/no-parent-name-construct-id-match.ts
- src/rules/require-passing-this.ts
> refactor: unify option type definitions and default options in rules

- .vscode/settings.json
- docs/.vitepress/config.mts
- docs/blog/2025-08-31.renamed-npm-package.md
- docs/ja/blog/2025-08-31.renamed-npm-package.md
> docs: add blog about renamed npm package

- docs/blog/2025-08-31.renamed-npm-package.md
- docs/ja/blog/2025-08-31.renamed-npm-package.md
> docs: fix yarn uninstall command in migration steps

- examples/flat-config/package.json
> fix: typo at package.json scripts
